### PR TITLE
Add AoE Avoidance for Hot Coals in MC

### PR DESCRIPTION
**Pull request by Day36512**
Majordomo Hot Coals damage avoidance.

### CODE REVIEW

**Comment by trickerer** [comment]
This is ok but why? Bots don't take damage from hot coals since it's a non-hunter trap type gameobject which does environmental damage and only targets players.

**Comment by Day36512** [comment]
Because tanks will simply sit in the coals if they end up there which is painful for melee players. I suppose a simple sendto command would work but this just avoids the issue altogether.

**Comment by kissingers** [comment]
sorry I have a crash but noway submit ,just add here
https://pastebin.com/9bWp6TMs

it seems crash from /src/server/game/AI/NpcBots/bot_ai.cpp:18636
now just at line 18637 add this but dont know is it right?
						if (!mineWP)
							continue;

**Comment by trickerer** [comment]
> sorry I have a crash but noway submit ,just add here https://pastebin.com/9bWp6TMs
> 
> it seems crash from /src/server/game/AI/NpcBots/bot_ai.cpp:18636 now just at line 18637 add this but dont know is it right? if (!mineWP) continue;

Issue tracker is here: https://github.com/trickerer/Trinity-Bots/issues. Your issue I think is https://github.com/trickerer/Trinity-Bots/issues/616

**Pull request merged**
